#!/bin/bash

# service user
id v2ray > /dev/null 2>&1 || adduser --system v2ray

# the binary executable
chmod +x /usr/bin/v2ray

# systemd
systemctl daemon-reload
systemctl enable v2ray
systemctl start v2ray
