name: Weekly Build

on:
  schedule:
    - cron: '0 7 * * 6'  # Run every Saturday at 7 AM UTC (Friday night US West)
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Run Docker build script
        run: ./build-docker.sh

  build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Run DEB build script
        run: ./build-deb.sh
      
      - name: Run RPM build script
        run: ./build-rpm.sh
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: build/
          retention-days: 30
